name: Release Linux AMD64 Binary

on:
  workflow_dispatch:  # 可以在网页手动触发

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Install Native Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev pkg-config

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build Web UI
        run: |
          cd web
          bun install
          bun run build
          cd ..

      - name: Build Binary
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 1
        run: |
          go build -ldflags="-s -w" -o flint .

      - name: Package Binary
        run: |
          zip -j flint-linux-amd64.zip flint

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flint-binary-linux-amd64
          path: flint-linux-amd64.zip
